name: bookify_audio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  flutter_riverpod: 
  google_fonts:
  cached_network_image: 
  path_provider:
  icons_launcher: 
  flutter_foreground_task:
  youtube_player_flutter:
  http:
  hive_ce: 
  hive_ce_flutter:
  youtube_player_iframe:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  build_runner:
  hive_ce_generator:


icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/splash.png
    - assets/data/library_bn.json
    - assets/data/library_en.json
    - CHANGELOG.md